- name: Run a multi-line script
  run: |
    echo Add other actions to build
    echo test, and deploy your project.
deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: "My first deploy step"
      run: I am deploying
